"""add workspaces and workspace_runs tables

Revision ID: 38334aa22aad
Revises: c3d4e5f6a7b8
Create Date: 2026-05-31 19:45:20.835956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38334aa22aad'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index('idx_workspaces_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('workspace_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_goal', sa.Text(), nullable=False),
    sa.Column('todo_md', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default='running', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('workspace_runs', schema=None) as batch_op:
        batch_op.create_index('idx_workspace_runs_ws_created', ['workspace_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_runs', schema=None) as batch_op:
        batch_op.drop_index('idx_workspace_runs_ws_created')

    op.drop_table('workspace_runs')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index('idx_workspaces_user_created')

    op.drop_table('workspaces')
    # ### end Alembic commands ###
