"""add report_name to reports

Revision ID: 44cb34acce18
Revises: 03d439cba9e5
Create Date: 2026-06-08 21:19:19.650044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44cb34acce18'
down_revision: Union[str, Sequence[str], None] = '03d439cba9e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('report_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'report_name')
    # ### end Alembic commands ###
