"""made query id as uuid fix

Revision ID: 59658b44aa1a
Revises: aca4d78f26ca
Create Date: 2026-06-07 00:03:05.439524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59658b44aa1a'
down_revision: Union[str, Sequence[str], None] = 'aca4d78f26ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Postgres won't implicitly cast VARCHAR -> UUID; spell out the conversion
    # of existing values with USING (the stored strings are valid UUIDs).
    op.alter_column('workspace_runs', 'query_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='query_id::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace_runs', 'query_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='query_id::text')
    # ### end Alembic commands ###
