"""add docs nodes pages tables queries

Revision ID: 7e73c03eb5f4
Revises: caafebe7ccf8
Create Date: 2026-05-22 13:44:34.040874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e73c03eb5f4'
down_revision: Union[str, Sequence[str], None] = 'caafebe7ccf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docs',
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('n_pages', sa.Integer(), nullable=True),
    sa.Column('n_tables', sa.Integer(), nullable=True),
    sa.Column('doc_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('doc_id')
    )
    with op.batch_alter_table('docs', schema=None) as batch_op:
        batch_op.create_index('idx_docs_ws', ['workspace_id'], unique=False)

    op.create_table('queries',
    sa.Column('query_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('doc_ids_used', sa.JSON(), nullable=True),
    sa.Column('table_ids_used', sa.JSON(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('citations_json', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('query_id')
    )
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.create_index('idx_queries_ws_user', ['workspace_id', 'user_id', 'created_at'], unique=False)

    op.create_table('nodes',
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('start_page', sa.Integer(), nullable=True),
    sa.Column('end_page', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('table_ids', sa.JSON(), nullable=True),
    sa.Column('child_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['docs.doc_id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('node_id')
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index('idx_nodes_ws_doc', ['workspace_id', 'doc_id'], unique=False)

    op.create_table('tables',
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('title_guess', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('columns_json', sa.JSON(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('xlsx_path', sa.Text(), nullable=True),
    sa.Column('parquet_path', sa.Text(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['docs.doc_id'], ),
    sa.PrimaryKeyConstraint('table_id')
    )
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.create_index('idx_tables_ws', ['workspace_id'], unique=False)

    op.create_table('pages',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('page_n', sa.Integer(), nullable=False),
    sa.Column('prose_text', sa.Text(), nullable=True),
    sa.Column('page_summary', sa.Text(), nullable=True),
    sa.Column('table_ids', sa.JSON(), nullable=True),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['docs.doc_id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('doc_id', 'page_n')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index('idx_pages_ws', ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index('idx_pages_ws')

    op.drop_table('pages')
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_index('idx_tables_ws')

    op.drop_table('tables')
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index('idx_nodes_ws_doc')

    op.drop_table('nodes')
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_index('idx_queries_ws_user')

    op.drop_table('queries')
    with op.batch_alter_table('docs', schema=None) as batch_op:
        batch_op.drop_index('idx_docs_ws')

    op.drop_table('docs')
    # ### end Alembic commands ###
