"""add xlsx_bytes to tables

Revision ID: af6d0b0c9fe0
Revises: 7e73c03eb5f4
Create Date: 2026-05-22 13:58:02.858333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af6d0b0c9fe0'
down_revision: Union[str, Sequence[str], None] = '7e73c03eb5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xlsx_bytes', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_column('xlsx_bytes')

    # ### end Alembic commands ###
