"""initial

Revision ID: bbd3ff78bc0d
Revises: 
Create Date: 2026-06-06 21:52:52.149732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbd3ff78bc0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docs',
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('n_pages', sa.Integer(), nullable=True),
    sa.Column('n_tables', sa.Integer(), nullable=True),
    sa.Column('doc_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default='ready', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index('idx_docs_ws', 'docs', ['workspace_id'], unique=False)
    op.create_table('queries',
    sa.Column('query_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('doc_ids_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('table_ids_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('citations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_index('idx_queries_ws_user', 'queries', ['workspace_id', 'user_id', 'created_at'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('target_length', sa.String(), server_default='standard', nullable=False),
    sa.Column('status', sa.String(), server_default='queued', nullable=False),
    sa.Column('outline_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('draft_md', sa.Text(), nullable=True),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('n_sections', sa.Integer(), server_default='0', nullable=False),
    sa.Column('n_words', sa.Integer(), server_default='0', nullable=False),
    sa.Column('n_hops', sa.Integer(), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index('idx_reports_ws_user', 'reports', ['workspace_id', 'user_id', 'created_at'], unique=False)
    op.create_table('workspaces',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_index('idx_workspaces_user_created', 'workspaces', ['user_id', 'created_at'], unique=False)
    op.create_table('nodes',
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('start_page', sa.Integer(), nullable=True),
    sa.Column('end_page', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('table_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('child_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['docs.doc_id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_index('idx_nodes_ws_doc', 'nodes', ['workspace_id', 'doc_id'], unique=False)
    op.create_table('tables',
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('title_guess', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('columns_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('xlsx_path', sa.Text(), nullable=True),
    sa.Column('xlsx_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('parquet_path', sa.Text(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['docs.doc_id'], ),
    sa.PrimaryKeyConstraint('table_id')
    )
    op.create_index('idx_tables_ws', 'tables', ['workspace_id'], unique=False)
    op.create_table('workspace_runs',
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('workspace', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('replans_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('replan_budget', sa.Integer(), server_default='3', nullable=False),
    sa.Column('todo_md', sa.Text(), nullable=True),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('query_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), server_default='running', nullable=False),
    sa.Column('query_counter', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_index('idx_workspace_runs_ws_created', 'workspace_runs', ['workspace_id', 'started_at'], unique=False)
    op.create_table('pages',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('page_n', sa.Integer(), nullable=False),
    sa.Column('prose_text', sa.Text(), nullable=True),
    sa.Column('page_summary', sa.Text(), nullable=True),
    sa.Column('table_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['docs.doc_id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('doc_id', 'page_n')
    )
    op.create_index('idx_pages_ws', 'pages', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pages_ws', table_name='pages')
    op.drop_table('pages')
    op.drop_index('idx_workspace_runs_ws_created', table_name='workspace_runs')
    op.drop_table('workspace_runs')
    op.drop_index('idx_tables_ws', table_name='tables')
    op.drop_table('tables')
    op.drop_index('idx_nodes_ws_doc', table_name='nodes')
    op.drop_table('nodes')
    op.drop_index('idx_workspaces_user_created', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('idx_reports_ws_user', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_queries_ws_user', table_name='queries')
    op.drop_table('queries')
    op.drop_index('idx_docs_ws', table_name='docs')
    op.drop_table('docs')
    # ### end Alembic commands ###
