"""workspace cascade FKs

Revision ID: cbe9dee89e18
Revises: 59658b44aa1a
Create Date: 2026-06-07 01:55:37.648047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbe9dee89e18'
down_revision: Union[str, Sequence[str], None] = '59658b44aa1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('docs_workspace_id_fkey', 'docs', 'workspaces', ['workspace_id'], ['workspace_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('nodes_doc_id_fkey'), 'nodes', type_='foreignkey')
    op.drop_constraint(op.f('nodes_parent_id_fkey'), 'nodes', type_='foreignkey')
    op.create_foreign_key('nodes_doc_id_fkey', 'nodes', 'docs', ['doc_id'], ['doc_id'], ondelete='CASCADE')
    op.create_foreign_key('nodes_parent_id_fkey', 'nodes', 'nodes', ['parent_id'], ['node_id'], ondelete='SET NULL')
    op.drop_constraint(op.f('pages_doc_id_fkey'), 'pages', type_='foreignkey')
    op.drop_constraint(op.f('pages_node_id_fkey'), 'pages', type_='foreignkey')
    op.create_foreign_key('pages_doc_id_fkey', 'pages', 'docs', ['doc_id'], ['doc_id'], ondelete='CASCADE')
    op.create_foreign_key('pages_node_id_fkey', 'pages', 'nodes', ['node_id'], ['node_id'], ondelete='SET NULL')
    op.create_foreign_key('queries_workspace_id_fkey', 'queries', 'workspaces', ['workspace_id'], ['workspace_id'], ondelete='CASCADE')
    op.create_foreign_key('reports_workspace_id_fkey', 'reports', 'workspaces', ['workspace_id'], ['workspace_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tables_doc_id_fkey'), 'tables', type_='foreignkey')
    op.create_foreign_key('tables_doc_id_fkey', 'tables', 'docs', ['doc_id'], ['doc_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tables_doc_id_fkey', 'tables', type_='foreignkey')
    op.create_foreign_key(op.f('tables_doc_id_fkey'), 'tables', 'docs', ['doc_id'], ['doc_id'])
    op.drop_constraint('reports_workspace_id_fkey', 'reports', type_='foreignkey')
    op.drop_constraint('queries_workspace_id_fkey', 'queries', type_='foreignkey')
    op.drop_constraint('pages_node_id_fkey', 'pages', type_='foreignkey')
    op.drop_constraint('pages_doc_id_fkey', 'pages', type_='foreignkey')
    op.create_foreign_key(op.f('pages_node_id_fkey'), 'pages', 'nodes', ['node_id'], ['node_id'])
    op.create_foreign_key(op.f('pages_doc_id_fkey'), 'pages', 'docs', ['doc_id'], ['doc_id'])
    op.drop_constraint('nodes_parent_id_fkey', 'nodes', type_='foreignkey')
    op.drop_constraint('nodes_doc_id_fkey', 'nodes', type_='foreignkey')
    op.create_foreign_key(op.f('nodes_parent_id_fkey'), 'nodes', 'nodes', ['parent_id'], ['node_id'])
    op.create_foreign_key(op.f('nodes_doc_id_fkey'), 'nodes', 'docs', ['doc_id'], ['doc_id'])
    op.drop_constraint('docs_workspace_id_fkey', 'docs', type_='foreignkey')
    # ### end Alembic commands ###
